///////////////////////////////////////////////////////////////////////////////
// File generated by HDevelop for HALCON/C++ Version 25.11.0.0
// Non-ASCII strings in this file are encoded in UTF-8.
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
///////////////////////////////////////////////////////////////////////////////
#include "HalconCpp.h"
#include "HDevThread.h"



using namespace HalconCpp;

namespace MyVision
{

//Note global variables cannot be shared across exports with different namespace

#ifndef NO_EXPORT_MAIN
// Main procedure 
void action()
{

  // Local iconic variables
  HObject  ho_Images, ho_ImageRed, ho_ImageGreen;
  HObject  ho_ImageBlue, ho_ImageSub1, ho_ImageSubFinal, ho_Regions;
  HObject  ho_ConnectedRegions, ho_RegionOpening, ho_RegionFillUp;
  HObject  ho_SelectedRegions, ho_RegionUnion, ho_DistanceImage;
  HObject  ho_DistanceImageUint2, ho_DistanceImageInvert, ho_Watersheds;
  HObject  ho_FinalCaps;

  // Local control variables
  HTuple  hv_Width, hv_Height, hv_WindowHandle;
  HTuple  hv_Number;

  //==========================================
  //1. 4K 图像采集与显示初始化
  //==========================================
  ReadImage(&ho_Images, "C:/Users/DrRowe/Downloads/Gemini_Generated_Image_7jxrsl7jxrsl7jxr.png");
  if (HDevWindowStack::IsOpen())
    CloseWindow(HDevWindowStack::Pop());
  GetImageSize(ho_Images, &hv_Width, &hv_Height);
  SetWindowAttr("background_color","black");
  OpenWindow(0,0,hv_Width/4,hv_Height/4,0,"visible","",&hv_WindowHandle);
  HDevWindowStack::Push(hv_WindowHandle);
  if (HDevWindowStack::IsOpen())
    SetPart(HDevWindowStack::GetActive(),0, 0, hv_Height-1, hv_Width-1);
  if (HDevWindowStack::IsOpen())
    DispObj(ho_Images, HDevWindowStack::GetActive());

  Decompose3(ho_Images, &ho_ImageRed, &ho_ImageGreen, &ho_ImageBlue);

  //==========================================
  //2. 目标提取（使用你要求的原子逻辑 1 & 2）
  //==========================================
  //--- 核心药方 1：增强蓝色识别 ---
  SubImage(ho_ImageBlue, ho_ImageRed, &ho_ImageSub1, 1, 0);
  SubImage(ho_ImageSub1, ho_ImageGreen, &ho_ImageSubFinal, 1, 0);

  //--- 核心药方 2：捕捉暗部蓝色 ---
  Threshold(ho_ImageSubFinal, &ho_Regions, 33, 255);
  Connection(ho_Regions, &ho_ConnectedRegions);
  OpeningCircle(ho_Regions, &ho_RegionOpening, 3.5);
  FillUp(ho_RegionOpening, &ho_RegionFillUp);
  Connection(ho_RegionFillUp, &ho_ConnectedRegions);

  //--- 核心药方 3：放宽筛选条件，确保 6 个全中 ---
  SelectShape(ho_ConnectedRegions, &ho_SelectedRegions, (HTuple("area").Append("circularity")), 
      "and", (HTuple(100).Append(0.2)), (HTuple(99999999).Append(1.0)));

  //==========================================
  //3. 核心：重叠分割逻辑 (原子逻辑 3 & 4)
  //==========================================
  //4. 再次执行分割（此时输入的是已经清理过干净的区域）
  Union1(ho_SelectedRegions, &ho_RegionUnion);
  DistanceTransform(ho_RegionUnion, &ho_DistanceImage, "euclidean", "true", hv_Width, 
      hv_Height);
  ConvertImageType(ho_DistanceImage, &ho_DistanceImageUint2, "uint2");
  InvertImage(ho_DistanceImageUint2, &ho_DistanceImageInvert);

  //5. 分水岭切割（把深度设大一点，防止把一个瓶盖切成两块）
  WatershedsThreshold(ho_DistanceImageInvert, &ho_Watersheds, 100);
  Intersection(ho_Watersheds, ho_RegionUnion, &ho_FinalCaps);

  //==========================================
  //4. 稳健结果显示 (解决 2454 句柄报错)
  //==========================================
  if (HDevWindowStack::IsOpen())
    DispObj(ho_Images, HDevWindowStack::GetActive());
  if (HDevWindowStack::IsOpen())
    SetColored(HDevWindowStack::GetActive(),12);
  if (HDevWindowStack::IsOpen())
    DispObj(ho_FinalCaps, HDevWindowStack::GetActive());

  CountObj(ho_FinalCaps, &hv_Number);
  //使用原生底层算子，确保显示稳定
  if (HDevWindowStack::IsOpen())
    DispText(HDevWindowStack::GetActive(),//'最终检测到蓝色瓶盖数量: '
      "\346\234\200\347\273\210\346\243\200\346\265\213\345\210\260\350\223\235\350\211\262\347\223\266\347\233\226\346\225\260\351\207\217: "+hv_Number, 
        "window", 12, 12, "black", HTuple(), HTuple());
}


#ifndef NO_EXPORT_APP_MAIN


} // end namespace

int main(int argc, char *argv[])
{
  int ret = 0;

  try
  {
#if defined(_WIN32)
    SetSystem("use_window_thread", "true");
#endif

    // Default settings used in HDevelop (can be omitted)
    SetSystem("width", 512);
    SetSystem("height", 512);

    MyVision::action();
  }
  catch (HException &exception)
  {
    fprintf(stderr,"  Error #%u in %s: %s\n", exception.ErrorCode(),
            exception.ProcName().TextA(),
            exception.ErrorMessage().TextA());
    ret = 1;
  }

#if defined(_WIN32)
  // On Windows socket communication is no longer possible after returning
  // from main, so HALCON cannot return floating licenses automatically.
  try
  {
    SetSystem("return_license", "true");
  }
  catch (...)
  {
    // Ignore any errors that might occur when returning the license.
  }
#endif

  return ret;
}
namespace MyVision
{


#endif


#endif


} // end namespace

